In [9]:
import pandas as pd 
import numpy as np

In [10]:
df = pd.read_csv("data/influencers.csv", index_col="id")
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

In [13]:
df_filtrado = df.dropna()
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,ALICANTE,sofiasantos,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,MADRID,adrianramos,389.0,258

In [16]:
df_filtrado = df.fillna(0)
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

Podemos indicar valores diferentes con fillna() para varias columnas.

In [17]:
df_filtrado = df.fillna({"retweets": 0, "mentions": -1})
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,ELCHE,dianapardo,12.0,129

Podemos filtrar por campos (Favoritos mayores a 400 y 20 menciones).

In [18]:
df[(df["favorites"] > 400) & (df["mentions"] > 20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,ALICANTE,cristianoronaldo,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183746,BORED AF,488.0,28.0,27.0,ELCHE,danicarvajal,21.0,2721

Tambien podemos utilizar string, por ejemplo, buscar un texto en una columna.

In [20]:
df[df["full_text"].str.contains("programming")]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,ALICANTE,sofiasantos,982.0,1822
183745,There is nothing better than programming!,424.0,110.0,29.0,ALICANTE,cristianoronaldo,82.0,351
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,ALICANTE,antoniamartinez,928.0,9918

Hemos visto como utilizar apply() con lambda.
Tambien podemos crear nuestrad funciones propias y recibir valores y llamarlos mediante apply().
Lo que recibamos es lo que se aplica en la colmna de llamada.

In [21]:
def multiplicarDoble(menciones):
    doble = menciones * 2
    return doble

df["mentions"] = df["mentions"].apply(multiplicarDoble)
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,20.0,MADRID,adrianramos,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,ALICANTE,sofiasantos,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,12.0,ELCHE,dianapardo,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,6.0,MADRID,luciaserrano,332.0,378
183725,Welcome back! 🙌,113.0,130.0,18.0,ELCHE,dianapardo,12.0,129

El siguiente ejemplo es enviar una fila completa del DataFrame en lugar del valor de una columna.
Se realiza indicando axis=1 al enviar la peticion.
Vamos a dividir (followees/followers) para saber la popularidad de una persona en una nueva columna.

In [22]:
def popularidad(fila):
    followees = fila["followees"]
    followers = fila["followers"]
    resultado = followees/followers
    return resultado

df["popularidad"] = df.apply(popularidad, axis=1)
df[df["popularidad"] >= 15]

,full_text,favorites,retweets,mentions,country,user,followers,followees,popularidad
id,,,,,,,,,
183735,Buy this product NOW!!,418.0,24.0,4.0,ELCHE,danicarvajal,21.0,2721,129.571429
183738,hmmm feeling bad today,296.0,93.0,58.0,ELCHE,danicarvajal,21.0,2721,129.571429
183746,BORED AF,488.0,28.0,54.0,ELCHE,danicarvajal,21.0,2721,129.571429

Podemos recuperar la media de una agrupacion, pero que solamente tenga en cuenta los valores tipo numero.

In [24]:
df.groupby(["country"]).mean(numeric_only=True)

           favorites   retweets  mentions  followers    followees  popularidad
country
ALICANTE  339.909091  91.272727     39.20    616.600  1889.363636     3.708644
ELCHE     294.857143  77.750000     27.50     15.375  1101.000000    55.308036
MADRID    186.375000  64.857143     23.75    360.500   318.000000     0.900897

Mediante agg() nos permite utilizar varias funciones de agrupacion a la vez.

In [27]:
grupo = df.groupby(["country"]).agg({
    "followers": "sum",
    "mentions": "mean", 
    "retweets": "max", 
})
grupo.head()

          followers  mentions  retweets
country
ALICANTE     6166.0     39.20     145.0
ELCHE         123.0     27.50     130.0
MADRID       2884.0     23.75     146.0

Podemos exportar los datos CSV/JSON

In [ ]:
grupo.to_csv("data/grupo.csv")
grupo.to_json("data/grupo.json")